# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAPP', '0005_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAPP.Season')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAPP.Shift')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAPP.Teacher')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
