# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAPP', '0006_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qb_title', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('is_password_protected', models.BooleanField()),
                ('qb_password', models.CharField(max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAPP.Teacher')),
            ],
        ),
    ]
