# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-14 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAPP', '0007_questionbank'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionbank',
            table='question_banks',
        ),
    ]
